#!/usr/bin/env node
'use strict'
// Regenerates games.js from whatever carts are sitting in this folder.
//
//     node build.js            add or refresh what has changed
//     node build.js --force    re-shoot every thumbnail
//
// A game is any .html that draws to a <canvas>. Its title and description are read out
// of its own <title> and <meta name="description">, so the whole workflow is: drop the
// cart in, run this, upload. Nothing to keep in sync by hand.
//
// Add <meta name="description" content="..."> to a cart to give it a blurb, and
// <meta name="hub" content="skip"> to keep a page out of the list.

const fs = require('fs')
const path = require('path')
const { execFileSync } = require('child_process')

const ROOT   = __dirname
const THUMBS = path.join(ROOT, 'thumbs')
const HUB    = path.join(ROOT, 'index.html')
const SKIP   = new Set(['node_modules', 'thumbs', '.git', '.vscode'])
const WINDOW = '800,750'        // 16:15, the same ratio as a 256x240 canvas
const BUDGET = '4000'           // ms of virtual time, so the cart gets to draw

// Windows ships one of these. Using the browser already on the machine beats pulling
// down a few hundred megabytes of Chromium just to take eight screenshots.
const BROWSER = [
  'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',
  'C:/Program Files/Microsoft/Edge/Application/msedge.exe',
  'C:/Program Files/Google/Chrome/Application/chrome.exe',
  'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe',
].find(p => fs.existsSync(p))

const force = process.argv.includes('--force')

function walk(dir) {
  const out = []
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (e.name.startsWith('.') || SKIP.has(e.name)) continue
    const full = path.join(dir, e.name)
    if (e.isDirectory()) out.push(...walk(full))
    else if (e.name.toLowerCase().endsWith('.html')) out.push(full)
  }
  return out
}

const meta = (html, name) => {
  const m = new RegExp('<meta[^>]+name=["\']' + name + '["\'][^>]*content=["\']([^"\']*)', 'i')
    .exec(html)
  return m ? m[1].trim() : ''
}

function shoot(src, png) {
  execFileSync(BROWSER, [
    '--headless=new', '--disable-gpu', '--hide-scrollbars', '--force-device-scale-factor=1',
    '--window-size=' + WINDOW, '--virtual-time-budget=' + BUDGET,
    '--screenshot=' + png,
    'file:///' + src.replace(/\\/g, '/'),
  ], { stdio: 'ignore' })
}

fs.mkdirSync(THUMBS, { recursive: true })

const games = []
for (const file of walk(ROOT).sort()) {
  if (file === HUB) continue
  const html = fs.readFileSync(file, 'utf8')
  if (meta(html, 'hub') === 'skip') continue
  if (!/<canvas[\s>]/i.test(html)) continue          // no canvas, not a cart

  const rel   = path.relative(ROOT, file).replace(/\\/g, '/')
  const slug  = rel.replace(/\.html$/i, '').replace(/\//g, '-')
  const title = ((/<title>([^<]*)<\/title>/i.exec(html) || [])[1] || slug).trim()
  const png   = path.join(THUMBS, slug + '.png')

  // re-shoot only when the cart is newer than its picture, so repeat runs are cheap
  let shot = false
  if (BROWSER && (force || !fs.existsSync(png) || fs.statSync(png).mtimeMs < fs.statSync(file).mtimeMs)) {
    try { shoot(file, png); shot = true }
    catch (err) { console.warn('  ! screenshot failed for ' + rel + ': ' + err.message) }
  }

  games.push({
    title,
    description: meta(html, 'description'),
    file: rel,
    thumb: fs.existsSync(png) ? 'thumbs/' + slug + '.png' : '',
  })
  console.log((shot ? 'shot  ' : 'keep  ') + rel.padEnd(26) + title)
}

games.sort((a, b) => a.title.localeCompare(b.title))

fs.writeFileSync(path.join(ROOT, 'games.js'),
  '// Generated by build.js - do not edit by hand. Run `node build.js` instead.\n' +
  'window.GAMES = ' + JSON.stringify(games, null, 2) + '\n')

console.log('\n' + games.length + ' games -> games.js')
if (!BROWSER) console.warn('No Edge or Chrome found, so thumbnails were skipped.')
