// Generated by build.js - do not edit by hand. Run `node build.js` instead.
window.GAMES = [
  {
    "title": "GALACTICA",
    "description": "A fixed-shooter in the Galaga mould: formations, dive runs, and the capture beam.",
    "file": "galactica.html",
    "thumb": "thumbs/galactica.png"
  },
  {
    "title": "SNAKE",
    "description": "",
    "file": "snake.html",
    "thumb": "thumbs/snake.png"
  }
]
