// Generated by build.js - do not edit by hand. Run `node build.js` instead.
window.GAMES = [
  {
    "title": "GALACTICA",
    "description": "A fixed-shooter in the Galaga mould: formations, dive runs, and the capture beam.",
    "file": "galactica.html",
    "thumb": "thumbs/galactica.png"
  },
  {
    "title": "RORSCHACH",
    "description": "A folded inkblot machine: mirrored blots, ten classic plates, a slow morphing flow, and a quiet NES-style drone.",
    "file": "rorschach.html",
    "thumb": "thumbs/rorschach.png"
  },
  {
    "title": "SNAKE",
    "description": "",
    "file": "snake.html",
    "thumb": "thumbs/snake.png"
  },
  {
    "title": "TETRO",
    "description": "NES-style block stacker with a hold slot, wall kicks and T-spins.",
    "file": "tetro.html",
    "thumb": "thumbs/tetro.png"
  }
]
